name       : haskell-multipart
version    : 0.1.2
release    : 2
source     :
    - http://hackage.haskell.org/package/multipart-0.1.2/multipart-0.1.2.tar.gz : e543fb307beb14fc366171d7767a6a18244bacf78db295d8d161c5c03d94043c
license    : BSD-3-Clause
component  : programming.haskell
summary    : HTTP multipart split out of the cgi package
description: |
    HTTP multipart split out of the cgi package
builddeps  :
    - ghc
    - haskell-cabal-install
    - haskell-parsec
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
