name       : haskell-multipart
version    : 0.2.0
release    : 5
source     :
    - https://hackage.haskell.org/package/multipart-0.2.0/multipart-0.2.0.tar.gz : d557bb13e957c4ae53b47a650da798c973002f680b4bc8ddbc9f00d9213286e7
license    : BSD-3-Clause
component  : programming.haskell
summary    : HTTP multipart split out of the cgi package
description: |
    HTTP multipart split out of the cgi package
builddeps  :
    - haskell-cabal-install
    - haskell-stringsearch-devel
rundeps    :
    - devel:
        - haskell-stringsearch-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
